### ISSUE TITLE
Error during mapping

### ISSUE THREAD

**Issue by fanatictentacle** [irtimmer/limelight-embedded#53]
I tried to map my Device a "Logitech Dual Action" Gamepad ... the following happened:

root@raspberrypi:/home/pi# java -jar limelight.jar map -input "/dev/input/js0" logi.map
Left Stick Right
Exception in thread "Input - Receiver" java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:506)
        at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
        at com.limelight.input.GamepadMapper.parseEvent(Unknown Source)
        at com.limelight.input.EvdevReader.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:744)

**Comment by irtimmer** [comment]
Joystick interface not supported
