### ISSUE TITLE
Error Code 522: GeForce Experience 2.1.5.0

### ISSUE THREAD

**Issue by PcInfamy** [irtimmer/limelight-embedded#68]
Im getting this error on GeForce Experience 2.1.5.0:

```
root@raspberrypi:/home/pi# java -jar limelight-pi.jar 192.168.1.22
Starting app
com.limelight.nvstream.http.GfeHttpResponseException: GFE error: Streaming session has failed due to a game management error. (Error code: 522)
        at com.limelight.nvstream.http.NvHTTP.verifyResponseStatus(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getXmlString(Unknown Source)
        at com.limelight.nvstream.http.PairingManager.getPairState(Unknown Source)
        at com.limelight.nvstream.http.NvHTTP.getPairState(Unknown Source)
        at com.limelight.nvstream.NvConnection.startApp(Unknown Source)
        at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
        at com.limelight.nvstream.NvConnection.access$300(Unknown Source)
        at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:744)
GFE error: Streaming session has failed due to a game management error. (Error code: 522)
Connection Error Starting app failed
```

Any thoughts?

**Comment by irtimmer** [comment]
Is a bug in GFE not in Limelight Embedded. You propably need to reinstall GFE/Steam

**Comment by PcInfamy** [comment]
Already tried that, didn't work.

**Comment by dodslaser** [comment]
The code seems to be pretty non-specific. I've been getting the same code when l launch while Kodi is running, or when the system is low on resources. Try killing all unnecessary processes.

**Comment by PcInfamy** [comment]
It's a fresh install of Raspian, there isn't anything else running really.

**Comment by dodslaser** [comment]
Reboot all equipment between the pi and your computer (including the pi and the computer). Remove *~/client.crt* *~/client.key* and *~/uniqueid.dat* on the pi. Clear the shield devices in GFE and try pairing it again. I know this sounds like a typical dumb IT-support solution, but it might just work.
